//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstData
    {
        public int ID { get; set; }
        public string NoKTP { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public string TempatLahir { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string NoHP { get; set; }
    }
}
